### PR TITLE
Adjusted to support OpenGL ES  targets

### PR DESCRIPTION
**Pull request by darmie**
Made a few changes and corrections to the definitions and config.

The test example is confirmed to work on Android target.

opengles_example_with_text

√ Changed data type for images and fonts to `cpp.Pointer<UInt8>` 
√ Loading fonts now work via the `Nvg.createFontMem()` without the need to modify the C files to support font loading from Android assets folder (see the new `test/snow_gles` example)

### CODE REVIEW

**Comment by ruby0x1** [comment]
Thanks! Can you undo the change to the test Main.hx? Maybe make a `test/snow_gles` duplicate instead, so that the desktop test still works as is.

**Comment by darmie** [comment]
@underscorediscovery I'll do that.

**Comment by darmie** [comment]
@underscorediscovery  I have made more changes to the PR, see commits. 

I would be glad if this PR is accepted, so that I can use this library for a framework I am developing.

**Comment by dazKind** [comment]
Looking fine. Merge incoming. 👍 
Though I haven't tested it bc I lack an android device. So if there are additional issues down the road, more fixes are welcome.

**Pull request merged**
